#1032 - update imputation flag default as auto
pharmaverse/admiral pull request #1061
Opened 2022-04-06 09:37 UTC by ClaudiaCarlucci

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/) 
- [x ] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [ x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation-1)?
- [ x] Update to all relevant roxygen headers and examples 
- [x ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ x] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md`
- [x ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [ x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue so that it closes after successful merging. 
- [ ] Address all merge conflicts and resolve appropriately 
- [ ] Pat yourself on the back for a job well done!  Much love to your accomplishment!

2022-04-06 12:19 UTC, ClaudiaCarlucci commented
@bms63 this is the right one. Apologies for the mistake in the other request

2022-04-06 12:23 UTC, bms63 commented on NEWS.md
> -
This isn't a change to function just to the template.  I think we can not include this in the news as it is not super important to the users.  Please remove.

2022-04-06 12:23 UTC, bms63 commented on man/adsl.Rd
> -An object of class \code{tbl_df} (inherits from \code{tbl}, \code{data.frame}) with 306 rows and 49 columns.
@thomas-neitmann I've seen this happen in another PR.  Is this worrisome?

2022-04-06 12:23 UTC, bms63 commented on man/reexports.Rd
> -  \item{rlang}{\code{\link[rlang]{exprs}}}
@thomas-neitmann I've seen this happen in another PR. Is this worrisome?

2022-04-06 12:24 UTC, bms63 requested changes
Hi Claudia.  Thanks for doing this!  I think we can remove this from news.  I want @thomas-neitmann to comment on these changes to the .Rd files as they are not related to the adeg templates.  Not sure why they are changing.

2022-05-16 12:55 UTC, bms63 commented
Hey Claudia.  Are you able to finish this PR today?  We have fixed a lot of the issues with the workflows/actions so hopefully my previous comments are not an issue anymore.  Please fix merge conflicts.

2022-05-16 19:31 UTC, bms63 commented
Hi Claudia, I fixed merged conflicts.

2022-05-16 19:32 UTC, bms63 commented
Unsure why so many .Rd files needed to get updated.  Can you look through them and see ift hey are just fomratting issues. thanks

2022-05-17 08:58 UTC, ClaudiaCarlucci commented
It's right, it's just formatting issues, nothing changed. Please let me know how I can proceed. Thanks

2022-05-17 13:14 UTC, bms63 commented
Please fix merge conflict and then I can re-approve to get the check_templates firing again.

2022-05-18 10:26 UTC, ClaudiaCarlucci commented
Hi @bms63 @millerg23 , It seems all checks went through. The merge is still blocked as Ben you requested some changes, is that okay now?

2022-05-18 10:30 UTC, millerg23 approved these changes
I will approve and see what happens, all looks good @ClaudiaCarlucci.
If not then Ben can approve and merge when he logs on later.

2022-05-18 12:00 UTC, merged