525 derivesummary
pharmaverse/admiral pull request #1118
Opened 2022-05-09 13:59 UTC by alanaharris22

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/) 
- [ ] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation-1)?
- [ ] Update to all relevant roxygen headers and examples 
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md`
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue so that it closes after successful merging. 
- [ ] Address all merge conflicts and resolve appropriately 
- [ ] Pat yourself on the back for a job well done!  Much love to your accomplishment!

2022-05-16 13:15 UTC, alanaharris22 commented
Hi @bms63, 
I'm still getting some errors with the filtering. I am looking into it now (have just added a new commit). I am probably missing something obvious, will keep you posted.

2022-06-01 09:28 UTC, alanaharris22 commented
Hi @bundfussr, 
The filtering seems to working fine now. Although there seems to be an issue with how `analysis_var` is called - would you mind taking a look? When running an example call of `derive_param_exposure` I get an error stating _'Quosures can only be unquoted within a quasiquotation context.'_, which goes back to `rlang:::Ops.quosure(analysis_var)` when using `last_trace()`. 
Thanks, 
Alana

2022-06-01 10:52 UTC, bundfussr commented
Hi @alanaharris22 , which example fails? I tried the examples on the header of the function but they failed with a different error.

2022-06-07 16:45 UTC, alanaharris22 commented
Hi @bundfussr, 
I used the example from line 76 to 105 in `derive_param_exposure()`, although since merging with devel I am now also getting a different error due to `list2()` - is this what you are getting too? 
Thanks, 
Alana

2022-06-14 11:17 UTC, alanaharris22 commented
Hi @bundfussr,
 
Sorry for the delay, the code is now working and is ready for review.

For reference I had to add a step in `derive_exposure_param()` to add the original variables in the input dataset to the dataset created by `get_summary_records`, since the code further down expected that these were present. Let me know if you think there's a better solution. 

I'm not sure why the `lint` check is failing though, if I run it directly in R it works fine? It seems there's an issue installing it, do you know what could be the problem?

Thanks, 
Alana

2022-06-14 11:27 UTC, bundfussr commented
It seems that a new version of lintr was released recently. The new version does not work with the version of packages we use for development.

@thomas-neitmann , I would suggest that we update the lintr workflow such that it does not use the most recent version of lintr but the one from `renv.lock`. This should make the workflow more stable and any findings from the workflow could be reproduced locally.

What do you think?

2022-06-14 13:06 UTC, thomas-neitmann commented
@bundfussr Let's do that! Feel free to approve this PR and ignore the failing lint workflow. I can go ahead and merge using admin privileges.

2022-06-14 15:18 UTC, bundfussr requested changes

2022-06-14 15:20 UTC, bms63 commented
Congrats on making the first update for `admiral 0.8.0` or at least `admiral > 0.7.0` !!   :)

2022-06-14 16:40 UTC, alanaharris22 commented on NEWS.md
> +
Sure, will update.

2022-06-14 16:40 UTC, alanaharris22 commented on NEWS.md
> +
Sure, will update.

2022-06-14 16:43 UTC, alanaharris22 commented on R/derive_param_exposure.R
> +    bind_rows(., dataset[0, ])
If I didn't have this here I found that the next section of code (lines 173 - 209) then failed as it expected the `add_data` dataset to have ASTDTM and AENDTM variables already.

2022-06-14 16:45 UTC, alanaharris22 commented on R/get_summary_records.R
> +#' @return A data frame with derived records appended to original dataset.
Yes, will remove this.

2022-06-14 16:45 UTC, alanaharris22 commented on R/get_summary_records.R
> +#' will be set to `NA`.
Yep, will remove this.

2022-06-14 16:52 UTC, alanaharris22 commented on R/get_summary_records.R
> +#' records has been added to a dataset.
Sure, will add.

2022-06-14 17:04 UTC, alanaharris22 commented on R/get_summary_records.R
> +#'
Sure, will do.

2022-06-15 09:06 UTC, bundfussr commented on R/derive_param_exposure.R
> +    bind_rows(., dataset[0, ])
I see. I guess
```
      mutate(
        ASTDTM = coalesce(ASTDTM, temp_start),
        AENDTM = coalesce(AENDTM, temp_end)
      ) %>%
```
is causing the failure.
However, why do we need `coalesce()`? `ASTDTM` and `AENDTM` are NA for all observations. So couldn't we simplify it to 
```
      mutate(
        ASTDTM = temp_start,
        AENDTM = temp_end
      ) %>%
```
and remove ` bind_rows(., dataset[0, ])`?

2022-08-25 10:25 UTC, alanaharris22 commented
@bundfussr - this PR is now ready to review, sorry for only getting to this now. Not sure why the check_templates isn't running though? 
Thanks!

2022-08-25 11:27 UTC, thomas-neitmann commented
"Check Templates" only runs once aomeone approves the PR which I just did 🙂

2022-08-25 11:28 UTC, thomas-neitmann approved these changes

2022-08-25 15:14 UTC, bms63 commented
> Hi @thomas-neitmann - it looks like check_templates is failing for ADLB, do you know if this is this an problem in other issues too? ad_adlb.R seems to run okay when I run in my R session. Thanks!

we jsut fixed this in another pr.  please merge idevel and you shoudl be good to go

2022-08-25 15:15 UTC, alanaharris22 commented
> > Hi @thomas-neitmann - it looks like check_templates is failing for ADLB, do you know if this is this an problem in other issues too? ad_adlb.R seems to run okay when I run in my R session. Thanks!
> 
> we jsut fixed this in another pr. please merge idevel and you shoudl be good to go

Thanks! Will do :)

2022-08-25 15:55 UTC, alanaharris22 commented
@thomas-neitmann @bms63 - would you mind approving the PR so check_templates runs? Thank you!

2022-08-25 16:04 UTC, thomas-neitmann approved these changes

2022-08-25 16:04 UTC, thomas-neitmann commented
Done.

2022-08-26 13:15 UTC, bms63 commented
@thomas-neitmann  Can we merge this one into devel?

2022-08-29 11:57 UTC, bms63 approved these changes
Approving for templates

2022-08-29 12:54 UTC, thomas-neitmann commented
@bundfussr Please approve as well. Currently merging is blocked due to your previous ask for changes.

2022-08-29 13:04 UTC, bundfussr approved these changes

2022-08-29 17:13 UTC, merged