1108 update references to admiraltest data
pharmaverse/admiral pull request #1121
Opened 2022-05-10 13:48 UTC by bms63

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/) 
- [ ] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation-1)?
- [ ] Update to all relevant roxygen headers and examples 
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md`
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue so that it closes after successful merging. 
- [ ] Address all merge conflicts and resolve appropriately 
- [ ] Pat yourself on the back for a job well done!  Much love to your accomplishment!

2022-05-10 13:53 UTC, bms63 commented
Hi all,

This PR changes a lot of files is small ways.  Hoping we can go over with a fine-tooth comb.

I'm still a bit flummoxed with the `create_query_data.R`  error.  If anyone has suggestions or can pull down and see if it works in there environment, then please! :)  
![image](https://user-images.githubusercontent.com/10111024/167645128-a0025e83-1e9c-4cce-acd5-ddcf65d4d996.png)

2022-05-10 14:03 UTC, thomas-neitmann requested changes

2022-05-10 14:03 UTC, thomas-neitmann commented on R/derive_var_extreme_date.R
> +#'   dataset_name = "admiral_ae",
The `dataset_name` should still just be `"ae"`. However, the list you pass as the `source_datasets` argument below should be `list(ae = admiral_ae)`.

2022-05-10 14:03 UTC, thomas-neitmann commented on R/derive_var_extreme_date.R
> +#'   dataset_name = "admiral_ae",
Same for all other dataset names.

2022-05-10 14:12 UTC, bms63 commented on inst/templates/ad_adae.R
>  ex <- convert_blanks_to_na(ex_single)
We were thinking that someone might grab that code for their work. So the person wouldn't have to change `admiral_ae `to `ae `in their code.

2022-05-10 14:19 UTC, thomas-neitmann commented on R/derive_var_extreme_date.R
> +#'     admiral_ae = admiral_ae, admiral_lb = admiral_lb),
Exactly!

2022-05-10 14:19 UTC, thomas-neitmann commented on inst/templates/ad_adae.R
>  ex <- convert_blanks_to_na(ex_single)
Alright, sounds good 👍

2022-05-10 14:33 UTC, thomas-neitmann commented
> Hi all,
> 
> This PR changes a lot of files is small ways. Hoping we can go over with a fine-tooth comb.
> 
> I'm still a bit flummoxed with the `create_query_data.R` error. If anyone has suggestions or can pull down and see if it works in there environment, then please! :) ![image](https://user-images.githubusercontent.com/10111024/167645128-a0025e83-1e9c-4cce-acd5-ddcf65d4d996.png)

That issues seems to have been resolved after Stefan's most recent changes on {admiraltest}. Getting this new error, through. Will fix it now. 
![image](https://user-images.githubusercontent.com/11788080/167653795-f502b350-d4d1-4469-a23d-fad5a590f601.png)

2022-05-10 14:36 UTC, bms63 commented
@thomas-neitmann Thanks Thomas.  Let me know when you have fixed it.  I made some of the changes you requested and will push up once your change is done.

2022-05-10 15:46 UTC, bms63 commented
@thomas-neitmann `devtools::check()` also runs for me with no issues.

2022-05-12 08:12 UTC, thomas-neitmann approved these changes

2022-05-12 09:18 UTC, merged