#1120 Update to add value_var parameter to derive_vars_atc()
pharmaverse/admiral pull request #1230
Opened 2022-06-22 10:33 UTC by tamarasenior

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [ ] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/) 
- [ ] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation-1)?
- [ ] Update to all relevant roxygen headers and examples 
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue in the Development Section on the right hand side.
- [ ] Address all merge conflicts and resolve appropriately 
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

2022-06-27 14:10 UTC, bundfussr requested changes

2022-06-27 14:10 UTC, bundfussr commented on R/derive_vars_transposed.R
> +      select(dataset_facm, !!!unname(by_vars), !!unname(value_var), FAGRPID, FATESTCD, FASTRESC),
`FASTRESC` should be removed.

2022-06-27 14:10 UTC, bundfussr commented on R/derive_vars_transposed.R
>  #'   `FASTRESC` are required
`FASTRESC` should be removed.

2022-07-04 09:11 UTC, rossfarrugia commented
@tamarasenior please can you make the requested updates to this PR. we need it merged for Roche ADCM to run

2022-07-05 16:43 UTC, tamarasenior commented
@rossfarrugia @bundfussr I've implemented the requested changes, but there is a broken link in devel that is causing one of the checks to fail

2022-07-06 07:15 UTC, rossfarrugia commented
@tamarasenior looks like https://r-pkgs.org/git.html is now a broken link in vignettes/git_usage.Rmd and i cant find an alternative left on that page. Can you delete the row as part of this PR please and that should solve it?

@thomas-neitmann @bms63 tagging as FYI in case you want the link replaced.

2022-07-06 10:57 UTC, bundfussr requested changes

2022-07-06 10:57 UTC, bundfussr commented on R/derive_vars_transposed.R
> +      select(dataset_facm, !!!unname(by_vars), !!unname(value_var), FAGRPID, FATESTCD),
`unname()` is not required for `value_var` because it isn't named anyway.

2022-07-21 06:36 UTC, rossfarrugia commented
@tamarasenior @bundfussr - can this one be approved and merged now? my Roche ADCM code fals over without it

2022-07-21 07:07 UTC, bundfussr approved these changes

2022-07-21 07:22 UTC, merged

2022-07-21 07:23 UTC, bundfussr commented
@rossfarrugia , sorry, I missed to re-review. It is merged now.