Use Admiral CI workflows
pharmaverse/admiral pull request #1385
Opened 2022-08-26 16:21 UTC by cicdguy

Use common Admiral CI workflows.

2022-08-26 16:22 UTC, cicdguy commented
An admin will need to change these settings in the branch protection settings, since the workflow names will change as a result of these common workflows.

<img width="741" alt="Screen Shot 2022-08-26 at 11 21 46 AM" src="https://user-images.githubusercontent.com/26552821/186949472-b46e552d-4d17-4bda-84f7-f23780151fe3.png">

2022-08-26 16:42 UTC, cicdguy commented on .github/workflows/common.yml
> +      skip-multiversion-docs: true
We will set this to `false` following the 0.9.0 release.

2022-08-29 08:13 UTC, thomas-neitmann requested changes
Thanks @cicdguy! Please take a look at my comments. In addition please merge in the latest changes from `devel`. That should fix the failing `Check Templates` workflow.

2022-08-29 08:13 UTC, thomas-neitmann commented on .github/workflows/common.yml
> +      - test
We don't have a `test` branch.

2022-08-29 08:13 UTC, thomas-neitmann commented on .github/workflows/common.yml
> +      - test
See comment above.

2022-08-29 08:13 UTC, thomas-neitmann commented on .github/workflows/common.yml
> +      r-version: $R_VERSION
Right now we only run this when a PR is approved as this takes up quite a bit of run time (and thus our free GA minutes).

2022-08-29 08:13 UTC, thomas-neitmann commented on .github/workflows/common.yml
> +    if: github.event_name == 'pull_request'
I assume that still runs on multiple R versions? What about the package versions? In our current `R CMD check` workflow we use MRAN snapshots from the date of the release of the tested R version. I'd very much like to continue doing that going forward.

2022-08-29 13:00 UTC, thomas-neitmann approved these changes

2022-08-29 13:00 UTC, merged