Patch
pharmaverse/admiral pull request #1442
Opened 2022-09-16 15:30 UTC by bms63

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/main/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [ ] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [ ] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/main/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/main/articles/programming_strategy.html#deprecation-1)?
- [ ] Update to all relevant roxygen headers and examples 
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue in the Development Section on the right hand side.
- [ ] Address all merge conflicts and resolve appropriately 
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

2022-09-16 15:32 UTC, bms63 commented
Hi all,  This will be `admiral 0.8.1` that addresses the hotfix for the bug identified by Ross and a few cosmetic changes for the website and readme

2022-09-16 15:40 UTC, bundfussr approved these changes

2022-09-16 18:04 UTC, bms63 commented
@thomas-neitmann  Hi Thomas.  If this looks good to you, then it can be tarred up and submitted to CRAN.

2022-09-16 18:06 UTC, bms63 commented on vignettes/contribution_model.Rmd
> + testing](https://pharmaverse.github.io/admiraldev/main/articles/unit_test_guidance.html).
```suggestion
 * Familiarize yourself with our [programming
 strategy](https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html),
 guidance for [GitHub
 usage](https://pharmaverse.github.io/admiraldev/devel/articles/git_usage.html)
 and [unit
 testing](https://pharmaverse.github.io/admiraldev/devel/articles/unit_test_guidance.html).
```

2022-09-16 18:07 UTC, bms63 commented on vignettes/contribution_model.Rmd
> + step-by-step guide.
```suggestion
 * Follow our [development
 process](https://pharmaverse.github.io/admiraldev/devel/articles/development_process.html)
 step-by-step guide.
```

2022-09-16 18:08 UTC, bms63 commented on vignettes/faq.Rmd
> + * Our [programming strategy](https://pharmaverse.github.io/admiraldev/main/articles/programming_strategy.html) serves as a framework
```suggestion
 * Our [programming strategy](https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html) serves as a framework
```

2022-09-16 18:09 UTC, bms63 commented on vignettes/faq.Rmd
> +* GitHub allows us through the Actions/Workflows to test `{admiral}` under several versions of R as well as several versions of dependent R packages needed for `{admiral}`.  Currently we test `{admir
```suggestion
* GitHub allows us through the Actions/Workflows to test `{admiral}` under several versions of R as well as several versions of dependent R packages needed for `{admiral}`.  Currently we test `{admiral}` against R Version 3.6.3 with a CRAN package snapshot from 2020-02-29, R Version 4.0 with a CRAN package snapshot from 2021-03-31 and the latest R version with the latest snapshots of packages.  You can view this workflow and others on our [admiralci GitHub Repository](https://github.com/pharmaverse/admiralci).
```

2022-09-19 08:25 UTC, thomas-neitmann requested changes

2022-09-19 08:25 UTC, thomas-neitmann commented on NEWS.md
> +that source observations where the date is `NA` are excluded (#1419).
```suggestion
- `derive_var_extreme_dt()` and `derive_var_extreme_dtm()` were updated such
that source observations where the date is `NA` are excluded (#1419)
```

We don't use full stops unless it's a multi-sentence paragraph.

2022-09-19 08:25 UTC, thomas-neitmann commented on tests/testthat/test-derive_var_extreme_date.R
> +test_that("derive_var_extreme_dt Test 3: NA dates are excluded", {
```suggestion
test_that("derive_var_extreme_dt Test 3: `NA` dates are excluded", {
```

2022-09-19 08:25 UTC, thomas-neitmann commented on tests/testthat/test-derive_var_extreme_date.R
> +test_that("derive_var_extreme_dtm Test 4: LSTALVDTM and traceability variables are derived", {
```suggestion
test_that("derive_var_extreme_dtm Test 4: `LSTALVDTM` and traceability variables are derived", {
```

2022-09-19 08:25 UTC, thomas-neitmann commented on tests/testthat/test-derive_var_extreme_date.R
> +test_that("derive_var_extreme_dtm Test 5: error is issued if DTC variable is specified", {
```suggestion
test_that("derive_var_extreme_dtm Test 5: error is issued if `--DTC` variable is specified", {
```

2022-09-19 13:34 UTC, bms63 commented
@thomas-neitmann Looks good to me.   Can you merge in as I created the PR

2022-09-19 13:40 UTC, thomas-neitmann approved these changes

2022-09-19 14:28 UTC, merged