Closes #1458 derive param exist flag@devel
pharmaverse/admiral pull request #1498
Opened 2022-10-07 20:59 UTC by jeffreyad

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/main/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [ ] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [ ] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/main/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/main/articles/programming_strategy.html#deprecation-1)?
- [ ] Update to all relevant roxygen headers and examples 
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue in the Development Section on the right hand side.
- [ ] Address all merge conflicts and resolve appropriately 
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

2022-10-07 21:21 UTC, bms63 commented
Hey Jeff.  You are need to change the branch to merge into - `devel` and not `main` .  I always look at the total number of files changed for a sanity check :)  
![image](https://user-images.githubusercontent.com/10111024/194655223-406d7d1f-6000-4ce3-a0b1-30a2ecbaa901.png)

2022-10-10 06:20 UTC, thomas-neitmann requested changes
Thanks a lot @jeffreyad! Just a minor comment from my side.

2022-10-10 06:20 UTC, thomas-neitmann commented on tests/testthat/test-derive_param_exist_flag.R
> +      )
No need to assign the output to a variable here.

```suggestion
    derive_param_exist_flag(
      dataset = adrs,
      dataset_adsl = adsl,
      dataset_add = adrs,
      filter_add = PARAMCD == "OVR",
      condition = AVALC == "PD",
      false_value = "N",
      set_values_to = vars(
        PARAMCD = "OVR",
        ANL01FL = "Y"
      )
```

2022-10-10 14:43 UTC, jeffreyad commented
> Thanks a lot @jeffreyad! Just a minor comment from my side.

Thanks, updated.

2022-10-10 14:44 UTC, thomas-neitmann commented on renv.lock
> +    "Version": "4.0.3",
```suggestion
    "Version": "3.6.3",
```

2022-10-10 14:45 UTC, thomas-neitmann approved these changes
Thanks a lot @jeffreyad, much appreciated!

2022-10-10 19:48 UTC, merged