Save all datasets in templates as .rds instead of .rda
pharmaverse/admiral pull request #1506
Opened 2022-10-11 17:33 UTC by nkr821

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/main/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [ ] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [ ] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/main/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/main/articles/programming_strategy.html#deprecation-1)?
- [ ] Update to all relevant roxygen headers and examples 
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue in the Development Section on the right hand side.
- [ ] Address all merge conflicts and resolve appropriately 
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

2022-10-13 06:19 UTC, thomas-neitmann requested changes

2022-10-13 16:37 UTC, nkr821 commented on inst/templates/ad_adae.R
> +save(adae, file = file.path(dir, "adae.rds"), compress = "bzip2")
saveRDS() does have a compress argument. I'll make the needed changes today

2022-10-14 05:15 UTC, thomas-neitmann requested changes
Thanks a lot for this update @nkr821! Can you also add an entry in the `NEWS.md` file?

2022-10-17 08:21 UTC, thomas-neitmann approved these changes
Thanks a lot @nkr821!

2022-10-17 08:23 UTC, thomas-neitmann commented
@nkr821 As a final step can you also follow these instructions such that the "Spell check" won't fail anymore:

```
Warning message:
In if (!is.na(exclusions)) removed <- lapply(Sys.glob(exclusions),  :
  the condition has length > 1 and only the first element will be used
  WORD  FOUND IN
rda   NEWS.md:25
rds   NEWS.md:25

Number of misspelled words: 2
You may correct the spellings of the words above or add them to the "inst/WORDLIST" file by running spelling::update_wordlist()
```

2022-10-25 17:52 UTC, bms63 commented
Hi @nkr821 can you fix these merge and Github Actions please.  Would like to get this merged into devel.  Thanks!!

2022-10-25 18:36 UTC, nkr821 commented
Hi @bms63, I'm still pretty new to Admiral, so I'm not sure what specifically needs to be done. I updated the WORDLIST file with the words failing the spellcheck, so I thought that would fix the problem, but I guess it is still not working. Any ideas on what to do next?

2022-10-25 18:41 UTC, bms63 commented on NEWS.md
> +- Templates now save datasets as .rds instead of .rda (#1501)
```suggestion
- Templates now save datasets as `.rds` instead of `.rda` (#1501)
```

2022-10-25 18:41 UTC, bms63 commented on NEWS.md
> +- Templates now save datasets as .rds instead of .rda (#1501)
Perhaps the backticks will fix this issue for us?

2022-10-25 19:21 UTC, bms63 commented
It worked!  Yay!  CAn you remove rda and rds from spell check list unless it is used somewhere else??  Also click the Update branch button so the latest devel updates come into your feature branch.

2022-10-25 20:36 UTC, nkr821 commented
Yay! Sounds good; I'll do that now

2022-10-25 21:33 UTC, nkr821 commented
@bms63 when I went to update the wordlist again, I started to get strange commit errors after making the change, and now my local branch is a total disaster, haha. If that's the only thing left to do for this issue, could we just leave them in there for now and I can update the wordlist on the next issue I work on? Thanks!

2022-10-26 12:15 UTC, bms63 commented
> @bms63 when I went to update the wordlist again, I started to get strange commit errors after making the change, and now my local branch is a total disaster, haha. If that's the only thing left to do for this issue, could we just leave them in there for now and I can update the wordlist on the next issue I work on? Thanks!

All good.  I fixed it up.  This is your first PR to admiral!!?? Congrats!

2022-10-26 15:49 UTC, merged

2022-10-26 17:21 UTC, nkr821 commented
Only my second PR. Thanks, @bms63 for your help!