Closes 1462 Increase test coverage for derive_param_tte
pharmaverse/admiral pull request #1508
Opened 2022-10-12 21:37 UTC by jeffreyad

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/main/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [ ] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [ ] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/main/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/main/articles/programming_strategy.html#deprecation-1)?
- [ ] Update to all relevant roxygen headers and examples 
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue in the Development Section on the right hand side.
- [ ] Address all merge conflicts and resolve appropriately 
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

2022-10-13 06:32 UTC, thomas-neitmann requested changes

2022-10-13 06:32 UTC, thomas-neitmann commented on tests/testthat/test-derive_param_tte.R
> +  )
If you check for a warning or error there's no need for an "expected" output apart from the `regexp` you define inside `expect_error()`.

```suggestion
  expect_error(
    list_tte_source_objects(package = "tte"),
    regexp = "No package called 'tte' is installed and hence no `tte_source` objects are available"
  )
```

2022-10-13 06:32 UTC, thomas-neitmann commented on tests/testthat/test-derive_param_tte.R
> +test_that("derive_param_tte Test 10: error is issued if package does not exist", {
```suggestion
test_that("list_tte_source_objects Test 1: error is issued if package does not exist", {
```

2022-10-13 15:09 UTC, jeffreyad commented
@thomas-neitmann added test 11 to cover code under # Get all `tte_source` objects exported by `package`.  Let me know if there is a better way to do this.  Thanks

![image](https://user-images.githubusercontent.com/112705781/195635140-d2a0b204-af7e-4d4b-bb02-65d3f0874bb6.png)

2022-10-13 15:16 UTC, thomas-neitmann commented
> @thomas-neitmann added test 11 to cover code under # Get all tte_source objects exported by package. Let me know if there is a better way to do this. Thanks

RIght now you're just checking whether the code runs without errors in test 11. What you'd rather want to do is define an `expected_output` and compare that against whatever `list_tte_source_objects()` returns.

2022-11-12 22:13 UTC, bms63 commented on tests/testthat/test-derive_param_tte.R
> +test_that("list_tte_source_objects Test 1: error is issued if package does not exist", {
```suggestion
test_that("list_tte_source_objects Test 10: error is issued if package does not exist", {
```

2022-11-12 22:14 UTC, bms63 commented on tests/testthat/test-derive_param_tte.R
> +test_that("list_tte_source_objects Test 2: expected objects produced", {
```suggestion
test_that("list_tte_source_objects Test 11: expected objects produced", {
```

2022-11-12 22:15 UTC, bms63 requested changes
couple of typos

2022-11-12 22:17 UTC, bms63 commented
@jeffreyad omg Jeff I thought I was going crazy!!!  I was like why did it auto-update...lol  probably should work on the weekend!!

2022-11-12 22:23 UTC, bms63 approved these changes
LGTM after the checks pass

2022-11-12 23:02 UTC, merged