Closes #1572 Consolidate new environment objects into admiral_environment
pharmaverse/admiral pull request #1595
Opened 2022-11-18 15:21 UTC by zdz2101

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/main/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/main/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/main/articles/programming_strategy.html#deprecation-1)?
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

2022-11-18 17:56 UTC, bms63 reviewed
Did we create any guidance around this in our developer vignettes?  This is all very new to me and I realize we have been using this method for a little while, but was unaware and makes me a little nervous.

2022-11-21 14:52 UTC, bundfussr approved these changes

2022-11-23 17:46 UTC, bundfussr approved these changes

2022-11-23 21:06 UTC, bms63 requested changes
Does this warrant a test that a new environment can be created?  I feel like this could be tested???  Or do the affected functions already have test coverages for new environments??

2022-11-23 21:42 UTC, zdz2101 commented
> Does this warrant a test that a new environment can be created?  I feel like this could be tested???  Or do the affected functions already have test coverages for new environments??

The affected functions' tests are already using this new consolidated environment object as well.

2022-11-24 01:13 UTC, bms63 commented on R/admiral_environment.R
> +######################################################
```suggestion
# To enhance features and add inputs as necessary 
```

2022-11-24 01:13 UTC, bms63 commented on R/admiral_environment.R
> +# 1. Add additional options such as future_input as shown commented above
```suggestion
# 1. Add additional options such as future_input as shown in comment above
```

2022-11-24 01:14 UTC, bms63 commented on R/admiral_environment.R
> +admiral_environment$duplicates <- NULL
Should we say something like See `... .R`  for usage

2022-11-24 01:17 UTC, bms63 approved these changes
So other musings...should this have a Roxygen header.  I'm not sure if it can be displayed on our reference documentation page, but it would be nice to showcase and point to this functionality a little more???  No problem if we jsut want to bury it. :)

2022-11-24 12:27 UTC, bundfussr commented
I think for developers and contributors it would be nice to have an overview of the objects in `admiral_environment` in the reference. But it should be clear that it is not of interest for users as they should never change or access these objects directly.

Most likely this requires a bit more of thought. There are more functions which are of interest for developers only, e.g, `assert_db_requirements()` or `extend_source_datasets()`. So maybe we could add a "Functions for developers and contributors" section in the next release (I think it's a bit late for this release).

2022-11-28 16:44 UTC, bms63 commented
@zdz2101 Can you add a roxygen header outlining what are goals are here with the enviroment.R file so it has a more standard feel to the file.  Use the `@nord` tag so it is not rendered onto our reference page.  This will be nice for developers and for developers who need a refresher on what this file is doing (like me).

2022-12-01 19:36 UTC, bms63 approved these changes
LGTM

2022-12-01 20:24 UTC, bms63 approved these changes
Just checking the Templates

2022-12-01 20:50 UTC, merged