Closes #1336 add NEWS.md update for basket_select()@devel
pharmaverse/admiral pull request #1607
Opened 2022-11-25 12:46 UTC by tamarasenior

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/main/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [ ] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [ ] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/main/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/main/articles/programming_strategy.html#deprecation-1)?
- [ ] Update to all relevant roxygen headers and examples 
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue in the Development Section on the right hand side.
- [ ] Address all merge conflicts and resolve appropriately 
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

2022-11-25 14:53 UTC, bundfussr requested changes

2022-11-25 14:53 UTC, bundfussr commented on NEWS.md
> +- Replace `smq_select()` and `sdg_select()` with `basket_select()` (#1597)
Could you move it to the "Breaking Changes" section?

And could you add the changes in `create_query_data()`, too?

2022-11-25 14:56 UTC, bundfussr commented
Depending on the feedback from Thomas and Ben we may need to add further changes. In principle we would need to deprecate the functions and arguments we have removed. But in this case it is quite complicated (see my comment in #1336).

2022-11-28 13:24 UTC, thomas-neitmann commented
Let's deprecate the old paramter by using `deprecate_stop()` and telling the user which parameters to use instead. No need to assign the old parameters to the new ones.

2022-11-29 16:22 UTC, bundfussr approved these changes
Well done!

2022-11-30 09:35 UTC, merged