Closes #1649 create vignette for pk programming
pharmaverse/admiral pull request #1651
Opened 2022-12-22 20:18 UTC by jeffreyad

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/devel/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [ ] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [ ] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/devel/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#deprecation)?
- [ ] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue in the Development Section on the right hand side.
- [ ] Address all merge conflicts and resolve appropriately 
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

2022-12-22 20:25 UTC, jeffreyad commented
This new vignette for PK ADNCA/ADPC programming requires the update to add nominal time to `create_single_dose_dataset()` #1643 #1640

2023-02-07 19:44 UTC, bms63 commented
Hey @jeffreyad lots of merge conflicts to fix.  Let me know if you need help.

2023-02-08 11:09 UTC, rossfarrugia requested changes
@jeffreyad nice vignette!! I'm not a PK expert so i only added some minor general updates for conventions we've tended to follow in the other vignettes/templates. Apologies for late comments, but some like removing the default argument lines you probably want to match in the template too which i saw was already merged at https://github.com/pharmaverse/admiral/pull/1700, so maybe just include those updates in this branch/PR if you agree.

@bundfussr if you get chance probably worth you taking a look at this new vignette, as you might spot some useful enhancements too from your experience writing these for some of the other ADaMs.

2023-02-08 11:09 UTC, rossfarrugia commented on vignettes/pk_adnca.Rmd
> +This section uses the `{admiral}` functions `derive_vars_merged`,
include `()` after each function name - won't repeat this comment again, trust you to double check and update any cases

2023-02-09 16:22 UTC, rossfarrugia commented on vignettes/pk_adnca.Rmd
> +    ignore_seconds_flag = FALSE,
@jeffreyad i still see these 2 arguments being set to same as default for these functions here and below - these lines could be removed

2023-02-09 16:37 UTC, jeffreyad commented
> thanks @jeffreyad for the updates! will you make the same updates to the adpc template to match here? good practice to keep our ADaM vignettes and respective template consistent.

Sure, thanks @rossfarrugia

2023-02-09 16:45 UTC, bms63 commented
> > thanks @jeffreyad for the updates! will you make the same updates to the adpc template to match here? good practice to keep our ADaM vignettes and respective template consistent.
> 
> Sure, thanks @rossfarrugia

Does that mean you will drop a lot of the timing variables in that template?  I thought those were needed for the analysis?  

Thanks again for pushing these through @jeffreyad!!

2023-02-09 16:50 UTC, jeffreyad commented
> > > thanks @jeffreyad for the updates! will you make the same updates to the adpc template to match here? good practice to keep our ADaM vignettes and respective template consistent.
> > 
> > 
> > Sure, thanks @rossfarrugia
> 
> Does that mean you will drop a lot of the timing variables in that template? I thought those were needed for the analysis?
> 
> Thanks again for pushing these through @jeffreyad!!

@bms63 No, it should just be removing the defaults for `flag_imputation`, `date_imputation`, and `ignore_seconds_flag`

2023-02-09 18:04 UTC, bms63 commented
@jeffreyad when you get a chance can you fix the man page errors.  I can re-approve so the templates fire off and then we can get this merged!!

2023-02-10 08:43 UTC, rossfarrugia approved these changes
Thanks for the updates @jeffreyad - fine from my perspective now, but will leave @bms63 to double check before merging.

2023-02-10 20:25 UTC, bms63 commented
Thanks @jeffreyad.  This new and updated templates are great addition for admiral!!

2023-02-10 20:25 UTC, merged

2023-02-13 09:57 UTC, thomas-neitmann commented
Thank you so much for all the effort you put into creating this @jeffreyad 🥳 👏