Closes #<1713> 1713 call convert blanks@devel
pharmaverse/admiral pull request #1770
Opened 2023-02-24 12:52 UTC by danleibovitz

2023-02-27 15:18 UTC, bms63 commented
Hi @danleibovitz where is the PR template and is this ready to review?

2023-03-02 02:43 UTC, bms63 requested changes
Thanks for doing this PR.  Since there is only one function involved we should just do `dm <- convert_blanks_to_na(admiral_dm)` rather than `dm <- admiral_dm %>% convert_blanks_to_na()`

2023-03-03 17:39 UTC, bms63 commented
@zdz2101 I changed a few lines here - can you just double check real quick.

@danleibovitz we got it from here.  trying to get all the PRs done in the next few hours.

2023-03-03 17:50 UTC, zdz2101 commented on vignettes/pk_adnca.Rmd
> +adsl <- admiral_adsl %>% convert_blanks_to_na()
To match consistency, remove this one too?

2023-03-03 18:29 UTC, zdz2101 commented on vignettes/pk_adnca.Rmd
> +adsl <- admiral_adsl %>% convert_blanks_to_na()
```suggestion
adsl <- admiral_adsl
```

2023-03-03 19:12 UTC, zdz2101 approved these changes

2023-03-03 19:50 UTC, merged