Closes #1747 Update: Following deprecation process for multiple funct…
pharmaverse/admiral pull request #1837
Opened 2023-03-27 18:26 UTC by sadchla-codes

…ions

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/devel/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/devel/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#deprecation)?
- [x] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

2023-03-27 19:18 UTC, bms63 reviewed
I think we want the deprecations tests to be moved into the test files and remove the `deprecation.R` file.  @bundfussr is that correct?

2023-03-27 20:21 UTC, bms63 commented
@sadchla-codes if only 1 test left, then lets move to correct file and remove this deprecation file.

2023-03-28 14:05 UTC, bundfussr requested changes

2023-03-29 14:48 UTC, zdz2101 requested changes
Small stuff, otherwise looks good

2023-03-29 14:48 UTC, zdz2101 commented on NEWS.md
> +`vars()` which was used in the admiral function calls that expected a list of quosures have being removed (#1747).
```suggestion
`vars()` which was used in the admiral function calls that expected a list of quosures has being removed (#1747).
```

2023-03-29 14:48 UTC, zdz2101 commented on NEWS.md
> +  - `derive_var_confirmation_flag()`
```suggestion
  - `derive_var_confirmation_flag()`
  - `filter_confirmation()`
```

Should this be included?

2023-03-29 15:32 UTC, bms63 commented
@sadchla-codes please merge - two approvals is good for me!!

2023-03-29 16:08 UTC, merged