1843 derive vars dt bug@devel
pharmaverse/admiral pull request #1849
Opened 2023-04-04 19:59 UTC by zdz2101

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/devel/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [ ] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [ ] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/devel/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#deprecation)?
- [ ] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue in the Development Section on the right hand side.
- [ ] Address all merge conflicts and resolve appropriately 
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

2023-04-04 20:01 UTC, zdz2101 commented
Hey @DeclanHodges can you try running your code(s) where you ran into issues using this [branch](https://github.com/pharmaverse/admiral/tree/1843_derive_vars_dt_bug%40devel)

2023-04-05 12:19 UTC, DeclanHodges commented
> Hey @DeclanHodges can you try running your code(s) where you ran into issues using this [branch](https://github.com/pharmaverse/admiral/tree/1843_derive_vars_dt_bug%40devel) , believe I addressed that case where user supplies both min/max dates and `highest_imputation = "Y"` and `date_imputation = "last"`, added a corresponding test but certainly need an extra pair of eyes

Hey @zdz2101, I reran my code and everything runs as expected now. Thanks for looking into this!

2023-04-05 17:28 UTC, bms63 commented on R/derive_date_vars.R
> +    stringr::str_starts(imputed_dtc, "(0000|9999)") | imputed_dtc %in% c("0000-01-01", "9999-12-31"), # nolint
Do we need the `strignr::` ?

2023-04-05 17:29 UTC, bms63 requested changes
News entry please :)

2023-04-06 12:21 UTC, DeclanHodges approved these changes
Looks good to me @zdz2101!

2023-04-09 20:45 UTC, bms63 approved these changes
Thanks Zelos!

2023-04-25 12:53 UTC, bms63 commented on NAMESPACE
> +importFrom(stringr,str_starts)
This is not done properly.  

```suggestion
importFrom(stringr, str_starts)
```

2023-04-25 13:04 UTC, bms63 commented on NAMESPACE
> +importFrom(stringr,str_starts)
I was doing this as an example @zdz2101

2023-04-26 17:59 UTC, bms63 commented
@zdz2101 We can merge this correct?  Or we were waiting on the expressions stuff?

2023-04-26 18:07 UTC, zdz2101 commented
> @zdz2101 We can merge this correct? Or we were waiting on the expressions stuff?

I think I needed a re-approval for check templates a while back but forgot to ping, should be good to go

2023-04-26 18:14 UTC, bms63 approved these changes

2023-04-26 18:47 UTC, merged