Closes #2254
pharmaverse/admiral pull request #2258
Opened 2023-11-28 15:34 UTC by manciniedoardo

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [ ] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [ ] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#deprecation)?
- [ ] Review the [Cheat Sheet](https://github.com/pharmaverse/admiral/blob/main/inst/cheatsheet/admiral_cheatsheet.pdf). Make any required updates to it by editing the file `inst/cheatsheet/admiral_cheatsheet.pptx` and re-upload a PDF version of it to the same folder.
- [ ] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md` under the header `# admiral (development version)` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/cran-release/reference/index.html)" page. 
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue in the Development Section on the right hand side.
- [ ] Address all merge conflicts and resolve appropriately
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

2023-11-28 18:55 UTC, bms63 commented on README.md
> +* Please see [FAQ: R and Package Versions](https://pharmaverse.github.io/admiral/articles/faq.html#why-do-we-use-a-certain-r-version-and-package-versions-for-development). for why we develop with cer
```suggestion
* Please see [FAQ: R and Package Versions](https://pharmaverse.github.io/admiral/articles/faq.html#why-do-we-use-a-certain-r-version-and-package-versions-for-development) for why we develop with certain R and package versions.
```

2023-11-28 18:57 UTC, bms63 requested changes
couple of minor updates

2023-11-28 18:58 UTC, bms63 reviewed
man pages action is failing

2023-11-29 10:48 UTC, manciniedoardo commented
> man pages action is failing

Fixed - links now failing but not sure if this is because I added a new page which is currently unpublished

2023-11-29 13:10 UTC, bms63 commented
> > man pages action is failing
> 
> Fixed - links now failing but not sure if this is because I added a new page which is currently unpublished

For it to become a webpage, we will  need to link it in the pkgdown yaml file so it publishes.

Maybe this should live over in admiraldiscovery instead of on admiral?

2023-11-29 13:19 UTC, bms63 commented
> > > > man pages action is failing
> > > 
> > > 
> > > Fixed - links now failing but not sure if this is because I added a new page which is currently unpublished
> > 
> > 
> > For it to become a webpage, we will need to link it in the pkgdown yaml file so it publishes.
> > Maybe this should live over in admiraldiscovery instead of on admiral?
> 
> My understanding was that admiraldiscovery would only be for the reactive function discovery table?

We can add whatever we want :)

2023-11-29 13:24 UTC, manciniedoardo commented
> > > > > man pages action is failing
> > > > 
> > > > 
> > > > Fixed - links now failing but not sure if this is because I added a new page which is currently unpublished
> > > 
> > > 
> > > For it to become a webpage, we will need to link it in the pkgdown yaml file so it publishes.
> > > Maybe this should live over in admiraldiscovery instead of on admiral?
> > 
> > 
> > My understanding was that admiraldiscovery would only be for the reactive function discovery table?
> 
> We can add whatever we want :)

True, personally I think its place is more in the "Community" tab though.

2023-11-29 13:37 UTC, bms63 commented on README.md
> +For a full collection of `{admiral}` conference presentations over the years, please travel to our [Presentation Archive](presentation_archive.html).
i think if you add `articles` to the front of the `presentation_archive.html`  it might work at the publishing time

2023-11-29 13:38 UTC, bms63 commented on README.md
> +For a full collection of `{admiral}` conference presentations over the years, please travel to our [Presentation Archive](presentation_archive.html).
but i think admiraldiscoverty might still be better

2023-11-29 13:49 UTC, bms63 commented
Discovering admiral!!  Feels to fit in nicely. but it is just a glorified web page that we link to

2023-11-29 13:50 UTC, manciniedoardo commented
> Discovering admiral!! Feels to fit in nicely. but it is just a glorified web page that we link to

Ok I'm swayed 😄 - will move!

2023-11-29 13:53 UTC, manciniedoardo commented
I guess the only slightly annoying thing is that then you are having to upkeep two pages for the same material - are you happy to then remove the 2023 conference presentation materials from this section also, and just link directly to admiraldiscovery?

2023-11-29 13:57 UTC, bms63 commented
> I guess the only slightly annoying thing is that then you are having to upkeep two pages for the same material - are you happy to then remove the 2023 conference presentation materials from this section also, and just link directly to admiraldiscovery?

Yeah!! lets just update in one place!!

2023-11-30 18:51 UTC, merged