2526 data raw data round 2
pharmaverse/admiral pull request #2527
Opened 2024-10-08 00:09 UTC by jimrothstein

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/CONTRIBUTING.html#detailed-development-process) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `main` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#deprecation)?
- [ ] Review the [Cheat Sheet](https://github.com/pharmaverse/admiral/blob/main/inst/cheatsheet/admiral_cheatsheet.pdf). Make any required updates to it by editing the file `inst/cheatsheet/admiral_cheatsheet.pptx` and re-upload a PDF and a PNG version of it to the same folder. (The PNG version can be created by taking a screenshot of the PDF version.)
- [ ] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [ x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md` under the header `# admiral (development version)` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers). A Developer Notes section is available in `NEWS.md` for tracking developer-facing issues.  
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue in the Development Section on the right hand side.
- [ ] Address all merge conflicts and resolve appropriately
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

2024-10-08 12:44 UTC, bms63 commented
Thanks @jimrothstein - did the scripts get re-run?  

I am wondering if there is some way to could apply a timestamp in the attributes of the datasets that could help us keep track of when this dataset was last created??  This way at least GitHub would detect the change in the timestamp as I am hoping the data doesn't change in the future - or if it does we know why!?!

@bundfussr WDYT?

2024-10-08 16:18 UTC, bundfussr commented
> I am wondering if there is some way to could apply a timestamp in the attributes of the datasets that could help us keep track of when this dataset was last created?? This way at least GitHub would detect the change in the timestamp as I am hoping the data doesn't change in the future - or if it does we know why!?!
> 
> @bundfussr WDYT?

@bms63 , what do you want to achieve?

If we add an attribute with a timestamp, git considers the file as changed even if the dataset was just recreated without any change (except the timestamp attribute). Therefore I'm not sure if this is a good idea.

I think we should rerun the `create_*` scripts before each release to ensure that the datasets are up to date (with respect to the pharmaversesdtm data and the `ad_` scripts).

2024-10-08 17:15 UTC, bms63 commented
> 
> @bms63 , what do you want to achieve?
> 

god-like powers.  :) 

I want some way to track when the datasets were last run.  if i see the datasets timestamp was run a couple of days before release then I will be happy.  if i see the datasest timestamp was run two months before the release then I will be sad and know I need to run them.

maybe we should just run them with a custom script with GHA with each PR????  maybe this is where diffdf could be used to give us a report of any changes occurring in vignettes where these datasets are being used?

simplest solution is just to add a checkbox in my release checklist :) https://github.com/pharmaverse/admiral/discussions/2394#discussion-6456043

2024-10-08 19:57 UTC, bms63 commented
@jimrothstein 

I realized I can see the timestamp in GitHub so the attributes update might be overkill 
![image](https://github.com/user-attachments/assets/b4b7b7c2-fb1b-470c-b77a-213fe65d3d4e)

@bundfussr 
Rein me in here!  I'm just a bit perplexed how our datasets got out of line with our templates code and looking for a way to prevent this in the future.

2024-10-09 10:03 UTC, bundfussr commented
> maybe we should just run them with a custom script with GHA with each PR???? maybe this is where diffdf could be used to give us a report of any changes occurring in vignettes where these datasets are being used?
> 
> simplest solution is just to add a checkbox in my release checklist :) [#2394 (comment)](https://github.com/pharmaverse/admiral/discussions/2394#discussion-6456043)

@bms63 , I wouldn't add an extra GHA for checking because the templates and pharmaversesdtm change rarely. Adding a checkbox to the release checklist seems the better option to me.

2024-10-09 12:21 UTC, bundfussr requested changes

2024-10-09 12:21 UTC, bundfussr commented on data-raw/create_admiral_adsl.R
Please update similar as suggested for `create_admiral_adlb.R`

2024-10-09 14:57 UTC, jimrothstein commented on data-raw/create_admiral_adsl.R
@bundfussr 
Changes made.   Code is better!  (Probably used `inner join` because saw this elsewhere)

One question:  adlb_old <- admiral::admiral_adlb
As soon as I run code locally then load_all(),  `old` is what I just ran (not original `old`)

2024-10-09 15:06 UTC, bundfussr commented on data-raw/create_admiral_adsl.R
> One question: adlb_old <- admiral::admiral_adlb
> As soon as I run code locally then load_all(), `old` is what I just ran (not original `old`)

Yes, that's correct. Is that an issue?

2024-10-09 15:14 UTC, bundfussr commented on data-raw/create_admiral_adlb.R
>  # To clarify directories (can be removed)
Code from line 5 to 19 should be removed (also in `create_admiral_adsl.R`).

2024-10-09 15:18 UTC, jimrothstein commented on data-raw/create_admiral_adsl.R
No, should not be issue .... 
also my latest push has link error in Readme
```
[<img src="http://pharmaverse.org/shields/admiral.svg">](https://pharmaverse.org)
```

2024-10-09 15:37 UTC, bms63 commented on data-raw/create_admiral_adsl.R
thats okay - it goes bad from time to time.

2024-10-09 16:39 UTC, bundfussr commented on data-raw/create_admiral_adsl.R
Hm, it's not related to your PR.

It seems that the files in the `shield` folder were removed (https://github.com/pharmaverse/pharmaverse/tree/gh-pages/shields).

@rossfarrugia , was this intended?

2024-10-09 16:58 UTC, bms63 commented on data-raw/create_admiral_adsl.R
https://github.com/pharmaverse/pharmaverse/issues/328

2024-10-09 16:59 UTC, bms63 commented on data-raw/create_admiral_adsl.R
maybe the culprit - no need to worry about this @jimrothstein we will get it sorted

2024-10-10 07:02 UTC, rossfarrugia commented on data-raw/create_admiral_adsl.R
Add that link to the ignored ones for now and we'll get the pharmaverse site fixed eventually for this, as per the issue Ben shared. We've been facing some back-end issues with the site and this bug came as a result but should be fixed this month.

2024-10-10 08:38 UTC, bundfussr commented on data-raw/create_admiral_adsl.R
The link check is not required, i.e., we can merge even if it fails. I would not add the link to the ignore file because then we need to remember to remove it later.

2024-10-10 08:46 UTC, rossfarrugia commented on data-raw/create_admiral_adsl.R
Up to you really. I was just thinking in case the fix takes longer and lots of PRs see the same. Plus that link has no real impact on the package anyway.

2024-10-17 21:29 UTC, bms63 commented on data-raw/create_admiral_adlb.R
Hey @jimrothstein did this get updated?

2024-10-17 22:07 UTC, jimrothstein commented on data-raw/create_admiral_adlb.R
> Hey @jimrothstein did this get updated?

Let me **double-check** everything ...  this weekend.

2024-10-22 23:49 UTC, jimrothstein commented
Created separate branch  for this issue/PR.

2024-10-25 20:45 UTC, closed without merging