Closes #2529 documentation add words to desription 2 functions
pharmaverse/admiral pull request #2574
Opened 2024-11-26 22:07 UTC by jimrothstein

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/CONTRIBUTING.html#detailed-development-process) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `main` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [ ] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#deprecation)?
- [ ] Review the [Cheat Sheet](https://github.com/pharmaverse/admiral/blob/main/inst/cheatsheet/admiral_cheatsheet.pdf). Make any required updates to it by editing the file `inst/cheatsheet/admiral_cheatsheet.pptx` and re-upload a PDF and a PNG version of it to the same folder. (The PNG version can be created by taking a screenshot of the PDF version.)
- [ ] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md` under the header `# admiral (development version)` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers). A Developer Notes section is available in `NEWS.md` for tracking developer-facing issues.  
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue in the Development Section on the right hand side.
- [ ] Address all merge conflicts and resolve appropriately
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

2024-11-27 23:04 UTC, jimrothstein commented
@manciniedoardo 

`derive_param_computed`  Added few words to `description`.  Any suggestions/improvements?
( Then will do `derive_vars_computed` the same.)   Thx

2024-11-29 16:16 UTC, manciniedoardo requested changes
Thanks @jimrothstein - a couple of comments but looks good.

2024-11-29 16:16 UTC, manciniedoardo commented on R/derive_param_computed.R
> +#' subtraction/difference, multiply/product, division/ratio,
```suggestion
#' subtraction/difference, multiplication/product, division/ratio,
```

2024-11-29 16:16 UTC, manciniedoardo commented on R/derive_param_computed.R
> +#' exponentiate/logarithm, or by formula.
```suggestion
#' exponentiation/logarithm, or by formula.
```

2024-11-29 16:16 UTC, manciniedoardo commented on DESCRIPTION
> +    person("Jim", "Rothstein", role = "aut",
great to have you on board 😄

2024-11-30 00:36 UTC, jimrothstein commented
![image](https://github.com/user-attachments/assets/5dda05c7-edae-4a2a-bb6c-88a12fc4dfe6)

2024-12-04 09:56 UTC, manciniedoardo approved these changes
Thanks @jimrothstein - i think the failing link is not from this PR - we can merge 😄

2024-12-04 09:57 UTC, merged