Closes #2577: Add unit tests for set_admiral_options
pharmaverse/admiral pull request #2589
Opened 2024-12-02 11:19 UTC by Anthogonyst

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/CONTRIBUTING.html#detailed-development-process) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `main` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#deprecation)?
- [x] Review the [Cheat Sheet](https://github.com/pharmaverse/admiral/blob/main/inst/cheatsheet/admiral_cheatsheet.pdf). Make any required updates to it by editing the file `inst/cheatsheet/admiral_cheatsheet.pptx` and re-upload a PDF and a PNG version of it to the same folder. (The PNG version can be created by taking a screenshot of the PDF version.)
- [ ] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` under the header `# admiral (development version)` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers). A Developer Notes section is available in `NEWS.md` for tracking developer-facing issues.  
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue in the Development Section on the right hand side.
- [ ] Address all merge conflicts and resolve appropriately
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

2024-12-02 13:41 UTC, bms63 commented
Umm...maybe we should re-look at the interactive portion of this function??

2024-12-02 13:52 UTC, manciniedoardo commented
Happy to reevaluate the testing for this function, but I do think the best place for it remains the admiral package itself.

2024-12-02 14:10 UTC, bms63 commented
> roxygen_param_by_vars

We should split out from this PR/ISsue as roxygen_param_by_vars was an experimental function.  We don't really have proper documentation for it.  Fine if we want to add tests to it, but we should probably also document it now that it is being used more 
 (https://github.com/pharmaverse/admiral/blob/main/R/roxygen2.R)

2024-12-12 10:29 UTC, manciniedoardo requested changes
Thanks @Anthogonyst look great! Just a minor comment.

2024-12-12 10:29 UTC, manciniedoardo commented on tests/testthat/test-admiral_options.R
> +## Test 7: set works ----
Minor comment: please update the title of Test 7 and Test 4 to be a bit more descriptive, i.e. specify which option you are testing?

2024-12-16 13:06 UTC, bms63 commented
@Anthogonyst are you able to complete this? - we split out the tests so this is the only one to complete now.

2024-12-20 19:39 UTC, Anthogonyst commented
Sure thing. Here you go, the test comments are updated.  @manciniedoardo @bms63

2024-12-20 19:45 UTC, bms63 approved these changes
Thanks!!   not sure what adventure you want to go on #2605 is a quick one but kind of interesting i think

2024-12-20 19:55 UTC, merged

2024-12-23 10:11 UTC, manciniedoardo commented
@Anthogonyst - totally up to you, but if you do want to pass us your name we can [acknowledge your contribution in the README](https://github.com/pharmaverse/admiral/pull/2621)

2024-12-28 00:20 UTC, Anthogonyst commented
@bms63 @manciniedoardo  If you can add my name as "Anthony Arroyo" in the contributions list, that would be great. I'm not entirely sure what my next steps are at the moment. Thank you.