745 add examples
pharmaverse/admiral pull request #891
Opened 2022-02-07 19:46 UTC by tomratford

closes #767

in line with #767 the examples for `format_reason_default` and `format_eoxxstt_default` is their parent function call to avoid confusion.

dev utilities `extend_source_datasets` and `filter_date_sources` were the only other functions without examples so I have added these based off other examples used within the other tte function examples.

---

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://roche-gsk.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/) 
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://roche-gsk.github.io/admiral/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://roche-gsk.github.io/admiral/articles/programming_strategy.html#deprecation-1)?
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::documents()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md`
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://roche-gsk.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue so that it closes after successful merging. 
- [x] Address all merge conflicts and resolve appropriately 
- [ ] Pat yourself on the back for a job well done!  Much love to your accomplishment!

2022-02-08 08:25 UTC, thomas-neitmann requested changes

2022-02-08 08:25 UTC, thomas-neitmann commented on R/derive_param_tte.R
> +#' "02",     ymd("2021-01-16"), ymd("2021-02-03")
Please indent by 2 spaces.

2022-02-08 08:25 UTC, thomas-neitmann commented on R/derive_param_tte.R
> +#' "02",     ymd("2021-01-16"), ymd("2021-02-03")
Please indent by 2 spaces.

2022-02-10 13:47 UTC, bms63 approved these changes
@thomas-neitmann I think this looks good - can we squeeze into 0.6.0 release?

2022-02-10 15:07 UTC, bms63 commented
@tomratford We might try and sneak this into the 0.6.0 release.  CAn you update the news please if they has not been done?

2022-02-10 18:51 UTC, thomas-neitmann requested changes

2022-02-10 18:51 UTC, thomas-neitmann commented on NEWS.md
> +- Examples have been added for `format_reason_default`, `format_eoxxstt_default`, `extend_source_datasets` and `filter_date_sources` (#745)
Please add a set of parentheses, i.e. `()`, after the function names.

2022-02-10 18:51 UTC, thomas-neitmann commented on R/derive_param_tte.R
> +#' library(lubridate, warn.conflicts = FALSE)
Same as above.

2022-02-10 18:51 UTC, thomas-neitmann commented on R/derive_var_disposition_status.R
> +#'   derive_disposition_status(
See comment above.

2022-02-10 18:51 UTC, thomas-neitmann commented on R/derive_vars_disposition_reason.R
> +#' `derive_disposition_reason()`.
The function has ben renamed to `derive_vars_disposition_reason()`.

2022-02-10 18:51 UTC, thomas-neitmann commented on R/derive_vars_disposition_reason.R
> +#' @seealso [derive_disposition_reason()]
See comment above.

2022-02-10 18:51 UTC, thomas-neitmann commented on R/derive_var_disposition_status.R
> +#' @seealso [derive_disposition_status()]
See comment above.

2022-02-11 11:48 UTC, thomas-neitmann approved these changes
Thank you!

2022-02-14 14:37 UTC, merged